
POST http://localhost:8080/establishments
Content-Type: application/json

[
  {
    "id": "153",
    "type": "DINING",
    "name": "P.O.D. Market1",
    "building": "0551",
    "room": "173",
    "url": "",
    "x": 29.64636443982178,
    "y": -82.34316087863382
  }
]