# GET http://localhost:8080/api/users

# POST http://localhost:8080/api/users
# Content-Type: application/json


#   {
#     "Username": "test9",
#     "Email": "manjarimisra94@gmail.com",
#     "Password": "Qwerty@123",
#     "FirstName": "ABCD",
#     "LastName": "XYZ1",
#     "Address" : "NewBerry Road",
#     "Verified": 3
#   }


DELETE http://localhost:8080//api/users/:test9
